### ISSUE TITLE
Koden stoppar

### ISSUE THREAD

**Issue by swegoat** [SwedishArtist/Tetris#4]
@itpastorn Utan att vi har, ändrar i någon funktion som kör själva spelet vägrar det starta och kastar felmeddelandet "matrix is null". Kan du ta en titt?
	matrix.forEach((row, y) => {

**Comment by itpastorn** [comment]
Fungerar för mig idag. Har ni ändringar som inte skickats upp till GitHub?

**Comment by swegoat** [comment]
Vi löste det på egen hand.

**Comment by itpastorn** [comment]
Sätt då detta ärende till löst
