### ISSUE TITLE
Bakgrund

### ISSUE THREAD

**Issue by swegoat** [SwedishArtist/Tetris#5]
@itpastorn då jag lade till reglerna:
#tetris {
	position: absolute;
	left: 50%;
}
på canvas-elementet i CSS började bakgrunden loopa över sig själv istället för att fylla skärmen som den ska.
Vet att vi haft samma problem innan men kommer inte ihåg hur vi löste det.

**Comment by itpastorn** [comment]
Ett block som har absolut positionering lyfts ut ur det normala flödet och bidrar inte längre till beräkningen av bredd och höjd hos det element som det är förankrat inom i HTML-koden.
